import { randomId } from './random-id';

/**
 * Generates function which silents global errors on page generated by scriptlet
 * If error doesn't belong to our error we transfer it to the native onError handler
 *
 * @param rid - unique identifier of scriptlet
 * @returns window.onerror handler
 */
export function createOnErrorHandler(rid: string): OnErrorEventHandlerNonNull {
    // eslint-disable-next-line consistent-return
    const nativeOnError = window.onerror;
    return function onError(error, ...args) {
        if (typeof error === 'string' && error.includes(rid)) {
            return true;
        }
        if (nativeOnError instanceof Function) {
            return nativeOnError.apply(window, [error, ...args]);
        }
        return false;
    };
}

/**
 * Silently aborts currently running script
 * TODO use this for other abort scriptlets
 *
 * @returns abort function
 */
export function getAbortFunc() {
    const rid = randomId();
    let isErrorHandlerSet = false;
    return function abort() {
        if (!isErrorHandlerSet) {
            window.onerror = createOnErrorHandler(rid);
            isErrorHandlerSet = true;
        }
        throw new ReferenceError(rid);
    };
}
