#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../@puppeteer+browsers@2.4.1/node_modules/@puppeteer/browsers/lib/cjs/main-cli.js" "$@"
else
  exec node  "$basedir/../../../../../@puppeteer+browsers@2.4.1/node_modules/@puppeteer/browsers/lib/cjs/main-cli.js" "$@"
fi
