---
version: 2
plan:
  project-key: AJL
  key: SCRIPSPECS
  name: scriptlets - test
variables:
  dockerPuppeteer: buildkite/puppeteer:5.2.1

stages:
  - Build:
      manual: 'false'
      final: 'false'
      jobs:
        - Build

Build:
  key: BUILD
  docker:
    image: "${bamboo.dockerPuppeteer}"
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x
            yarn install
            yarn test
            yarn browserstack
            yarn build
            yarn wiki:check-updates

        environment: BROWSERSTACK_USER="${bamboo.browserstackUser}" \
                     BROWSERSTACK_KEY="${bamboo.browserstackPassword}"
  final-tasks:
    - clean
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://jirahub.service.eu.consul/v1/webhook/bamboo

labels: []
other:
  concurrent-build-plugin: system-default
