---
version: 2
plan:
  project-key: AJL
  key: SCRIPTLETSINCR
  name: scriptlets - increment
variables:
  dockerContainer: adguard/node-ssh:18.19--0

stages:
  - Increment:
      manual: true
      final: false
      jobs:
        - Increment

Increment:
  key: INCR
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            #!/bin/bash
            set -e -f -u -x

            # Explicitly checkout the revision that we need.
            git checkout "${bamboo.repository.revision.number}"

            # do not increment for dist deploy after release build
            if ! [[ `git log -1 --pretty=%s` =~ "deploy: update dist" ]];then
              git checkout master
              set -e
              set -x
              ls -alt
              pnpm increment
            fi
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

labels: []
other:
  concurrent-build-plugin: system-default
