---
version: 2
plan:
  project-key: AJL
  key: SCRIPTLETSINCR
  name: scriptlets - increment
variables:
  dockerContainer: adguard/node-ssh:15.14--6

stages:
  - Increment:
      manual: 'false'
      final: 'false'
      jobs:
        - Increment

Increment:
  key: INCR
  docker:
    image: "${bamboo.dockerContainer}"
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # do not increment for dist deploy after release build
            if [[ `git log -1 --pretty=%B` == "deploy: update dist" ]];then
              set -e
              set -x
              ls -alt
              yarn increment
            fi
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          commitMessage: 'skipci: Automatic increment build number'
          selectedRepository: defaultRepository
  requirements:
    - adg-docker: 'true'

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

labels: []
other:
  concurrent-build-plugin: system-default
