---
version: 2
plan:
  project-key: AJL
  key: SCRIPTLETSTEST
  name: scriptlets - test new
variables:
  dockerPuppeteer: adguard/puppeteer-runner:22.14--24.5--1

stages:
  - Build: &stage
      manual: false
      final: false
      jobs:
        - Build docs
        - Build lib
  - Lint and test:
      <<: *stage
      jobs:
        - Test qunit
        - Test vitest
        - Test smoke
        # lint should be run after building of docs and lib
        - Lint

Build docs:
  key: BUILDDOCS
  docker: &docker
    image: "${bamboo.dockerPuppeteer}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script: &setup-script
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x

            ls -laht

            # Fix mixed logs
            exec 2>&1

            # Exclude '--ignore-scripts' from pnpm arguments
            # since it prevents postinstall scripts from running
            # so Chrome is not installed which is crucial for tests
            originalPnpmArgs="$bamboo_varsPnpm"
            modifiedPnpmArgs=$(echo "$originalPnpmArgs" | sed 's/--ignore-scripts//g')

            # Install common dependencies
            pnpm install ${modifiedPnpmArgs}
    - script:
        interpreter: SHELL
        scripts:
          - |-
            # build docs to lint them later
            # check compatibility table updates and build it and build wiki docs
            pnpm wiki
  final-tasks:
    - script: &cleanup-script
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements: &requirements
    - extension: 'true'

Build lib:
  key: BUILDLIB
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - |-
            pnpm build
  artifacts:
    - name: scriptlets.corelibs.json
      location: dist
      pattern: scriptlets.corelibs.json
      required: true
    - name: redirects.json
      location: dist
      pattern: redirects.json
      required: true
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh dist/scriptlets.corelibs.json,dist/redirects.json"
  requirements: *requirements

Test qunit:
  key: TESTQUNIT
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - |-
            pnpm test:qunit
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

Test vitest:
  key: TESTVITEST
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - |-
            pnpm test:vitest
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

Test smoke:
  key: TESTSMOKE
  docker: *docker
  tasks:
    - checkout:
        force-clean-build: true
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - |-
            pnpm test:smoke
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

Lint:
  key: LINT
  docker: *docker
  tasks:
    - checkout
    - script: *setup-script
    - script:
        interpreter: SHELL
        scripts:
          - |-
            pnpm lint
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]
other:
  concurrent-build-plugin: system-default
