---
version: 2
plan:
  project-key: AJL
  key: SCRIPTLETSTEST
  name: scriptlets - test new
variables:
  dockerPuppeteer: adguard/puppeteer-runner:23.3--1

stages:
  - Build:
      manual: 'false'
      final: 'false'
      jobs:
        - Build

Build:
  key: BUILD
  docker:
    image: "${bamboo.dockerPuppeteer}"
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -e
            set -x
            ls -alt

            pnpm install

            # TODO fix building wiki, ubo changed format of their source
            # # build docs to lint them later
            # # check compatibility table updates and build it and build wiki docs
            # pnpm wiki

            pnpm test
            pnpm build

            # lint code and docs. it should be run after `pnpm build`
            pnpm lint
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: scriptlets.corelibs.json
      location: dist
      pattern: scriptlets.corelibs.json
      required: true
    - name: redirects.json
      location: dist
      pattern: redirects.json
      required: true
  requirements:
    - adg-docker: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo

labels: [ ]
other:
  concurrent-build-plugin: system-default
