---
version: 2
plan:
  project-key: AJL
  key: SCRIPTLETSTEST
  name: scriptlets - test new

stages:
  - Build: &stage
      manual: false
      final: false
      jobs:
        - Build docs
        - Build lib
  - Lint and test:
      <<: *stage
      jobs:
        - Test qunit
        - Test vitest
        - Test smoke
        # lint should be run after building of docs and lib
        - Lint

Build docs:
  key: BUILDDOCS
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            # Fix mixed logs
            exec 2>&1

            export DOCKER_BUILDKIT=1

            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg BUILD_RUN_ID=${bamboo.buildNumber} \
              --target wiki-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script: &cleanup-script
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh"
  requirements: &requirements
    - extension: 'true'

Build lib:
  key: BUILDLIB
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            # Fix mixed logs
            exec 2>&1

            export DOCKER_BUILDKIT=1

            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg BUILD_RUN_ID=${bamboo.buildNumber} \
              --target build-output \
              --output type=local,dest=output \
              .
  artifacts:
    - name: scriptlets.corelibs.json
      location: output/artifacts
      pattern: scriptlets.corelibs.json
      required: true
    - name: redirects.json
      location: output/artifacts
      pattern: redirects.json
      required: true
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - "./bamboo-specs/scripts/cleanup.sh output/artifacts/scriptlets.corelibs.json,output/artifacts/redirects.json"
  requirements: *requirements

Test qunit:
  key: TESTQUNIT
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            # Fix mixed logs
            exec 2>&1

            export DOCKER_BUILDKIT=1

            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg BUILD_RUN_ID=${bamboo.buildNumber} \
              --target test-qunit-output \
              --output type=local,dest=output \
              .
    - script:
        interpreter: SHELL
        scripts:
          - |-
            if [ -f output/exit-code.txt ]; then
              exit $(cat output/exit-code.txt)
            fi
            echo "output/exit-code.txt not found"
            exit 1
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

Test vitest:
  key: TESTVITEST
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            # Fix mixed logs
            exec 2>&1

            export DOCKER_BUILDKIT=1

            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg BUILD_RUN_ID=${bamboo.buildNumber} \
              --target test-vitest-output \
              --output type=local,dest=output \
              .
    - script:
        interpreter: SHELL
        scripts:
          - |-
            if [ -f output/exit-code.txt ]; then
              exit $(cat output/exit-code.txt)
            fi
            echo "output/exit-code.txt not found"
            exit 1
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

Test smoke:
  key: TESTSMOKE
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            # Fix mixed logs
            exec 2>&1

            export DOCKER_BUILDKIT=1

            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg BUILD_RUN_ID=${bamboo.buildNumber} \
              --target test-smoke-output \
              --output type=local,dest=output \
              .
    - script:
        interpreter: SHELL
        scripts:
          - |-
            if [ -f output/exit-code.txt ]; then
              exit $(cat output/exit-code.txt)
            fi
            echo "output/exit-code.txt not found"
            exit 1
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

Lint:
  key: LINT
  other:
    clean-working-dir: true
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -ex

            # Fix mixed logs
            exec 2>&1

            export DOCKER_BUILDKIT=1

            docker build \
              --file Dockerfile \
              --progress plain \
              --build-arg BUILD_RUN_ID=${bamboo.buildNumber} \
              --target lint-output \
              --output type=local,dest=output \
              .
  final-tasks:
    - script: *cleanup-script
  requirements: *requirements

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

labels: [ ]
other:
  concurrent-build-plugin: system-default
