name: Build Scriptlets

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.jobs
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: yarn install
        run: yarn install

      - name: yarn test
        run: yarn test

      - name: yarn browserstack
        run: yarn browserstack
        if:
          ${{ github.event_name == 'push' ||
              github.event.pull_request.head.repo.full_name == github.repository
          }}

      - name: yarn corelibs
        run: yarn corelibs

      - name: yarn build
        run: yarn build

      - name: yarn wiki:check-updates
        run: yarn wiki:check-updates

  notify:
    needs:
      - build

    if:
      ${{ always() &&
        (
          github.event_name == 'push' ||
          github.event.pull_request.head.repo.full_name == github.repository
        )
      }}
    runs-on: ubuntu-latest
    steps:
      - name: Conclusion
        uses: technote-space/workflow-conclusion-action@v1
      - name: Send Slack notif
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ env.WORKFLOW_CONCLUSION }}
          fields: repo, message, commit, author, job
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
